[build]
  publish = "."

[[headers]]
  for = "/index.html"
  [headers.values]
  Cache-Control = "no-store, no-cache, must-revalidate, max-age=0"

[[headers]]
  for = "/*"
  [headers.values]
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "SAMEORIGIN"
